import { buildValues } from "./build";
import { toYaml } from "./yaml";
import { commonSubtree, deepMerge, isPlainObject, subtractDefaults } from "./values";
import type { ArgocdTree } from "../../../server/types";
import type { Values } from "./values";

/**
 * The GitOps tree: catalog state in, the files a values repo holds out.
 *
 * The layout and the merge order are `convert_to_universal_chart.py`'s
 * (`build_applicationset`, `build_root_application`), because a tree authored
 * here and a tree converted there land in the same repo and are read by the
 * same ApplicationSet:
 *
 *   defaults.yaml -> <ns>/defaults.yaml -> base/<release>.yaml -> <ns>/values/<release>.yaml
 *
 * Argo merges those in order, last wins.
 */

export type GeneratedFile = {
  path: string;
  text: string;
  /** One line under the file name in the preview switcher. */
  note: string;
};

const HEADER = "# Generated by the portal's ArgoCD builder. Layered values — see root-application.yaml.";

const IGNORED_SECURITY_PATHS = [
  ".spec.template.spec.securityContext.runAsUser",
  ".spec.template.spec.securityContext.runAsGroup",
  ".spec.template.spec.securityContext.fsGroup",
  ".spec.template.spec.securityContext.seLinuxOptions",
  ".spec.template.spec.containers[]?.securityContext.runAsUser",
  ".spec.template.spec.containers[]?.securityContext.capabilities",
];

/**
 * Admission mutates fields Helm's desired manifest never sets (SCC-assigned
 * runAsUser/fsGroup, controller-populated ServiceAccount secrets), and a
 * StatefulSet's volumeClaimTemplates are immutable after creation. Without
 * these, self-heal fights the cluster's own controllers and the Application
 * flips OutOfSync -> Synced every reconcile.
 */
function ignoreDifferences(): Values[] {
  return [
    { group: "apps", kind: "Deployment", jqPathExpressions: IGNORED_SECURITY_PATHS },
    { group: "apps", kind: "StatefulSet", jqPathExpressions: [...IGNORED_SECURITY_PATHS, ".spec.volumeClaimTemplates"] },
    { group: "apps", kind: "DaemonSet", jqPathExpressions: IGNORED_SECURITY_PATHS },
    { group: "", kind: "ServiceAccount", jsonPointers: ["/secrets", "/imagePullSecrets"] },
  ];
}

/** `$values/<path>`, honouring a tree folded into a subdirectory of a bigger repo. */
function valuesRef(valuesPath: string, rest: string): string {
  const prefix = valuesPath ? `${valuesPath.replace(/^\/+|\/+$/g, "")}/` : "";
  return `$values/${prefix}${rest}`;
}
function repoPath(valuesPath: string, rest: string): string {
  const prefix = valuesPath ? `${valuesPath.replace(/^\/+|\/+$/g, "")}/` : "";
  return `${prefix}${rest}`;
}

/** A release's file name, and the ApplicationSet's `{{release}}`. */
export function slug(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "release"
  );
}

/**
 * Every path a document defines, as dotted strings — used to keep a shared
 * namespace override out of `<ns>/defaults.yaml` when a base file already sets
 * the same path. Namespace defaults are merged *below* base, so a value
 * promoted there would be silently overwritten by the base it was meant to
 * override.
 */
function paths(doc: Values, prefix = ""): Set<string> {
  const out = new Set<string>();
  for (const [k, v] of Object.entries(doc)) {
    const p = prefix ? `${prefix}.${k}` : k;
    out.add(p);
    if (isPlainObject(v)) paths(v, p).forEach((c) => out.add(c));
  }
  return out;
}

/** Drop from `doc` every path any base file already claims. */
function withoutClaimed(doc: Values, claimed: Set<string>, prefix = ""): Values {
  const out: Values = {};
  for (const [k, v] of Object.entries(doc)) {
    const p = prefix ? `${prefix}.${k}` : k;
    if (isPlainObject(v)) {
      const sub = withoutClaimed(v, claimed, p);
      if (Object.keys(sub).length) out[k] = sub;
    } else if (!claimed.has(p)) {
      out[k] = v;
    }
  }
  return out;
}

/** A values file always exists, even when it is empty: a missing valueFile fails the whole render. */
function valuesFile(path: string, doc: Values, header: string, note: string): GeneratedFile {
  const body = Object.keys(doc).length ? toYaml(doc) : "{}";
  return { path, text: `${header}\n${body}\n`, note };
}

export function buildTree(tree: ArgocdTree): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const releases = tree.releases.filter((r) => r.name.trim());
  const namespaces = tree.namespaces.filter((n) => n.name.trim());
  const valuesPath = tree.values.path ?? "";

  // ---- base layer -------------------------------------------------------
  const base = new Map<string, Values>();
  releases.forEach((r) => base.set(r.id, buildValues(r.features, r.extraValues)));

  // What every release shares goes into the one file below all of them.
  const globalDefaults = commonSubtree([...base.values()]);
  const claimed = new Set<string>();
  base.forEach((doc) => paths(doc).forEach((p) => claimed.add(p)));

  files.push(
    valuesFile(
      "defaults.yaml",
      globalDefaults,
      `${HEADER}\n# GLOBAL defaults — identical across every release in this tree.`,
      "shared by every release"
    )
  );

  releases.forEach((r) => {
    const doc = subtractDefaults(base.get(r.id) ?? {}, globalDefaults);
    files.push(
      valuesFile(
        `base/${slug(r.name)}.yaml`,
        doc,
        `${HEADER}\n# ${r.name} — environment-agnostic values, shared by every namespace that runs it.`,
        "environment-agnostic"
      )
    );
  });

  // ---- namespace layers -------------------------------------------------
  namespaces.forEach((ns) => {
    // A namespace runs every release in the tree; an entry only carries what it
    // overrides. So the pointer and values files are written for all of them —
    // a release with nothing to override still has to be in the fan-out, and
    // the ApplicationSet reads `<ns>/releases/*.yaml` to find it.
    const fragments = new Map<string, Values>();
    releases.forEach((r) => {
      const entry = ns.releases.find((e) => e.release === r.id);
      fragments.set(r.id, entry ? buildValues(entry.features, entry.extraValues) : {});
    });

    // Shared across this namespace's releases AND not claimed by any base file
    // — see `withoutClaimed`: base merges after namespace defaults, so a
    // colliding key promoted here would never take effect.
    const nsDefaults = withoutClaimed(
      subtractDefaults(commonSubtree([...fragments.values()]), globalDefaults),
      claimed
    );

    files.push(
      valuesFile(
        `${ns.name}/defaults.yaml`,
        nsDefaults,
        `${HEADER}\n# ${ns.name} — settings identical across this namespace's releases.`,
        `${ns.name} · shared`
      )
    );

    releases.forEach((release) => {
      const below = deepMerge(deepMerge(globalDefaults, nsDefaults), base.get(release.id) ?? {});
      const doc = subtractDefaults(fragments.get(release.id) ?? {}, below);
      files.push(
        valuesFile(
          `${ns.name}/values/${slug(release.name)}.yaml`,
          doc,
          `${HEADER}\n# ${release.name} in ${ns.name} — only what differs. Applied last, so it wins.`,
          `${ns.name} · overrides`
        )
      );
      files.push({
        path: `${ns.name}/releases/${slug(release.name)}.yaml`,
        // Not a values file: the ApplicationSet's git *files* generator reads
        // one of these per release, and `{{release}}` is this file's content.
        text: `release: ${slug(release.name)}\n`,
        note: "ApplicationSet pointer",
      });
    });

    files.push({
      path: `${ns.name}/${ns.name}-applicationset.yaml`,
      text: `${HEADER}\n${toYaml(applicationSet(tree, ns.name, valuesPath))}\n`,
      note: `one Application per release in ${ns.name}`,
    });
  });

  files.push({
    path: "root-application.yaml",
    text: `${rootHeader(tree)}\n${toYaml(rootApplication(tree, valuesPath))}\n`,
    note: "the one object you apply by hand",
  });

  return files;
}

function applicationSet(tree: ArgocdTree, namespace: string, valuesPath: string): Values {
  return {
    apiVersion: "argoproj.io/v1alpha1",
    kind: "ApplicationSet",
    metadata: { name: `${namespace}-microservices`, namespace: "argocd" },
    spec: {
      // A files generator, not directories: base/ and <ns>/values/ are flat, so
      // there is no directory per release to enumerate. `{{release}}` comes
      // from each pointer file's own content, which is what keeps
      // base/{{release}}.yaml and <ns>/values/{{release}}.yaml consistent.
      generators: [
        {
          git: {
            repoURL: tree.values.repoUrl,
            revision: tree.values.revision,
            files: [{ path: repoPath(valuesPath, `${namespace}/releases/*.yaml`) }],
          },
        },
      ],
      template: {
        metadata: {
          name: `${namespace}-{{release}}`,
          labels: { namespace, "managed-by": "universal-chart" },
          annotations: { "argocd.argoproj.io/sync-wave": "0" },
        },
        spec: {
          project: "default",
          sources: [
            {
              repoURL: tree.chart.repoUrl,
              targetRevision: tree.chart.revision,
              path: tree.chart.path,
              helm: {
                // Low to high precedence. Every one of these files is written,
                // empty ones included — a valueFiles entry that does not exist
                // fails the whole render.
                valueFiles: [
                  valuesRef(valuesPath, "defaults.yaml"),
                  valuesRef(valuesPath, `${namespace}/defaults.yaml`),
                  valuesRef(valuesPath, "base/{{release}}.yaml"),
                  valuesRef(valuesPath, `${namespace}/values/{{release}}.yaml`),
                ],
              },
            },
            { repoURL: tree.values.repoUrl, targetRevision: tree.values.revision, ref: "values" },
          ],
          destination: { server: "https://kubernetes.default.svc", namespace },
          syncPolicy: {
            automated: { prune: true, selfHeal: true },
            syncOptions: ["CreateNamespace=true", "ServerSideApply=true"],
          },
          ignoreDifferences: ignoreDifferences(),
        },
      },
    },
  };
}

function rootHeader(tree: ArgocdTree): string {
  return [
    "# ROOT app-of-apps: the ONE object you apply by hand. It deploys every",
    "# <namespace>-applicationset.yaml in this tree, so bootstrapping is",
    "#",
    `#     kubectl apply -f root-application.yaml`,
    "#",
    "# and nothing else. Adding a namespace or a release later is a git commit.",
    "#",
    "# prune is false on purpose: pruning one ApplicationSet would cascade into",
    "# deleting every Application it generated and every workload those deploy.",
    `# It matches itself, so editing ${tree.rootAppName} in git reconciles without another apply.`,
  ].join("\n");
}

function rootApplication(tree: ArgocdTree, valuesPath: string): Values {
  return {
    apiVersion: "argoproj.io/v1alpha1",
    kind: "Application",
    metadata: { name: tree.rootAppName || "platform-root", namespace: "argocd" },
    spec: {
      project: "default",
      destination: { server: "https://kubernetes.default.svc", namespace: "argocd" },
      // A directory source, not Helm: these files are finished Kubernetes
      // objects, not a chart to render.
      source: {
        repoURL: tree.values.repoUrl,
        targetRevision: tree.values.revision,
        path: valuesPath || ".",
        directory: {
          recurse: true,
          // Argo matches these against paths relative to source.path and a
          // single `*` spans directory levels, so include alone is unsafe: a
          // release named `web-application` makes <ns>/values/web-application.yaml
          // match, and Argo would apply a values file as a manifest.
          include: "{*applicationset.yaml,*application.yaml}",
          exclude: "{base/*,*/values/*,*/releases/*}",
        },
      },
      syncPolicy: { automated: { prune: false, selfHeal: true }, syncOptions: ["ServerSideApply=true"] },
    },
  };
}
