import { buildValues } from "./build";
import { toYaml } from "./yaml";
import { deepMerge, subtractChartDefaults } from "./values";
import { FEATURES, defaultValues } from "./catalog";
import type { ArgocdTree } from "../../../server/types";
import type { Values } from "./values";

/** What every feature writes when merely switched on — the chart's own answers. */
const CHART_DEFAULTS: Values = FEATURES.reduce<Values>(
  (acc, f) => deepMerge(acc, buildValues({ [f.id]: { on: true, v: defaultValues(f.id) } })),
  {}
);

/**
 * The GitOps tree: catalog state in, the files a values repo holds out.
 *
 * The layout and the merge order are `convert_to_universal_chart.py`'s, because
 * a tree authored here and a tree converted there land in the same repo and are
 * read by the same wiring:
 *
 *   base/<release>.yaml -> <ns>/defaults.yaml -> <ns>/values/<release>.yaml
 *
 * Argo merges those in order, last wins.
 *
 * That chain is no longer written into this tree. It lives in the
 * `ms-applicationSet` chart in the universal-chart repo, which the root
 * ApplicationSet renders once per namespace directory:
 *
 *   root-application.yaml       applied by hand, once
 *     root-applicationSet.yaml  one Application per namespace directory
 *       ms-applicationSet       one ApplicationSet per namespace
 *         one Application per <ns>/values/*.yaml
 *
 * Neither root file is written here: the Application/ApplicationSet that
 * deploy a values repo belong to whoever runs ArgoCD, set up once, not to
 * every tree. `importTree` still reads them from a repo that has them.
 *
 * So adding a namespace is adding a directory and adding a release is adding a
 * file — neither needs a new manifest. Gone with the old per-namespace
 * ApplicationSets: the `<ns>/releases/*.yaml` pointer files (the fan-out globs
 * `<ns>/values/*.yaml` directly now) and the tree-root `defaults.yaml` (no
 * layer in the chain reads one, so anything common across namespaces is
 * repeated per namespace instead — which is where the tree's own defaults go:
 * into every `<ns>/defaults.yaml`, layered right over base).
 */

export type GeneratedFile = {
  path: string;
  text: string;
  /** One line under the file name in the preview switcher. */
  note: string;
};

const HEADER = "# Generated by the portal's ArgoCD builder. Layered: base -> <ns>/defaults.yaml -> <ns>/values.";


/**
 * Directories at the tree root that are not namespaces. `base/` holds the
 * shared release files; the other three only ever appear in converter output,
 * and are excluded here anyway so a portal tree committed alongside one keeps
 * the same root ApplicationSet.
 */
export const NON_NAMESPACE_DIRS = ["base", "cluster-shared", "ERRORS_ANALYSIS", "report"];

/** A release's file name — the same in `base/` and `<ns>/values/`, which is what keeps the chain consistent. */
export function slug(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "release"
  );
}

/** A values file always exists, even when it is empty: a missing valueFile fails the whole render. */
function valuesFile(path: string, doc: Values, header: string, note: string): GeneratedFile {
  const body = Object.keys(doc).length ? toYaml(doc) : "{}";
  return { path, text: `${header}\n${body}\n`, note };
}

export function buildTree(tree: ArgocdTree): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const releases = tree.releases.filter((r) => r.name.trim());
  const namespaces = tree.namespaces.filter((n) => n.name.trim());

  // ---- base layer -------------------------------------------------------
  // Written whole. There is no tree-root defaults.yaml to subtract against —
  // the chart's chain starts at base/<release>.yaml, and subtracting against a
  // layer nobody applies silently drops the value.
  const base = new Map<string, Values>();
  releases.forEach((r) => base.set(r.id, buildValues(r.features, r.extraValues)));

  releases.forEach((r) => {
    files.push(
      valuesFile(
        `base/${slug(r.name)}.yaml`,
        base.get(r.id) ?? {},
        `${HEADER}\n# ${r.name} — environment-agnostic values, shared by every namespace that runs it.`,
        "environment-agnostic"
      )
    );
  });

  // ---- namespace layers -------------------------------------------------
  namespaces.forEach((ns) => {
    // A namespace runs every release in the tree but its `absent` ones; an entry only carries what it
    // overrides. The values file is written for all of them either way — its
    // existence in `<ns>/values/` is what puts the release in the fan-out, so a
    // release with nothing to override still needs an (empty) file.
    const fragments = new Map<string, Values>();
    releases.forEach((r) => {
      const entry = ns.releases.find((e) => e.release === r.id);
      fragments.set(r.id, entry ? buildValues(entry.features, entry.extraValues) : {});
    });

    // Exactly what was set for this namespace — nothing is promoted into it.
    // A value several microservices happen to share stays in each one's own
    // file, where it was typed: a defaults file holding values nobody put there
    // is a file nobody can explain.
    const nsDefaults = buildValues(ns.defaults?.features ?? {}, ns.defaults?.extraValues);

    files.push(
      valuesFile(
        `${ns.name}/defaults.yaml`,
        nsDefaults,
        `${HEADER}\n# ${ns.name} — defaults for every microservice in this namespace.\n# Layered over base/<release>.yaml and under ${ns.name}/values/<release>.yaml.`,
        `${ns.name} · defaults`
      )
    );

    releases.forEach((release) => {
      if (ns.absent?.includes(release.id)) return;
      // The chain's own order: base, then this namespace's defaults over it.
      const below = deepMerge(base.get(release.id) ?? {}, nsDefaults);
      const doc = subtractChartDefaults(fragments.get(release.id) ?? {}, below, CHART_DEFAULTS);
      files.push(
        valuesFile(
          // Back where it was read from: a grouping sub-folder is kept.
          `${ns.name}/values/${ns.groups?.[release.id] ? `${ns.groups[release.id]}/` : ""}${slug(release.name)}.yaml`,
          doc,
          `${HEADER}\n# ${release.name} in ${ns.name} — what this namespace sets. Applied last, so it wins.`,
          `${ns.name} · overrides`
        )
      );
    });
  });

  return files;
}
