import { buildValues } from "./build";
import { toYaml } from "./yaml";
import { commonSubtree, deepMerge, isPlainObject, subtractDefaults } from "./values";
import type { ArgocdTree } from "../../../server/types";
import type { Values } from "./values";

/**
 * The GitOps tree: catalog state in, the files a values repo holds out.
 *
 * The layout and the merge order are `convert_to_universal_chart.py`'s, because
 * a tree authored here and a tree converted there land in the same repo and are
 * read by the same wiring:
 *
 *   <ns>/defaults.yaml -> base/<release>.yaml -> <ns>/values/<release>.yaml
 *
 * Argo merges those in order, last wins.
 *
 * That chain is no longer written into this tree. It lives in the
 * `ms-applicationSet` chart in the universal-chart repo, which the root
 * ApplicationSet renders once per namespace directory:
 *
 *   root-application.yaml       applied by hand, once
 *     root-applicationSet.yaml  one Application per namespace directory
 *       ms-applicationSet       one ApplicationSet per namespace
 *         one Application per <ns>/values/*.yaml
 *
 * So adding a namespace is adding a directory and adding a release is adding a
 * file — neither needs a new manifest. Gone with the old per-namespace
 * ApplicationSets: the `<ns>/releases/*.yaml` pointer files (the fan-out globs
 * `<ns>/values/*.yaml` directly now) and the tree-root `defaults.yaml` (no
 * layer in the chain reads one, so anything common across namespaces is
 * repeated per namespace instead).
 */

export type GeneratedFile = {
  path: string;
  text: string;
  /** One line under the file name in the preview switcher. */
  note: string;
};

const HEADER = "# Generated by the portal's ArgoCD builder. Layered values — see root-application.yaml.";

/** The converter's own defaults, and not worth a field until someone needs another value. */
const ARGOCD_NAMESPACE = "argocd";
const PROJECT = "default";
const DESTINATION_SERVER = "https://kubernetes.default.svc";
const ROOT_APPSET_FILE_NAME = "root-applicationSet.yaml";

/**
 * Directories at the tree root that are not namespaces. `base/` holds the
 * shared release files; the other three only ever appear in converter output,
 * and are excluded here anyway so a portal tree committed alongside one keeps
 * the same root ApplicationSet.
 */
const NON_NAMESPACE_DIRS = ["base", "cluster-shared", "ERRORS_ANALYSIS", "report"];

/** `<values path>/<rest>`, honouring a tree folded into a subdirectory of a bigger repo. */
function repoPath(valuesPath: string, rest: string): string {
  const prefix = valuesPath ? `${valuesPath.replace(/^\/+|\/+$/g, "")}/` : "";
  return `${prefix}${rest}`;
}

/** A release's file name — the same in `base/` and `<ns>/values/`, which is what keeps the chain consistent. */
export function slug(name: string): string {
  return (
    name
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "release"
  );
}

/**
 * Every path a document defines, as dotted strings — used to keep a shared
 * namespace override out of `<ns>/defaults.yaml` when a base file already sets
 * the same path. Namespace defaults are merged *below* base, so a value
 * promoted there would be silently overwritten by the base it was meant to
 * override.
 */
function paths(doc: Values, prefix = ""): Set<string> {
  const out = new Set<string>();
  for (const [k, v] of Object.entries(doc)) {
    const p = prefix ? `${prefix}.${k}` : k;
    out.add(p);
    if (isPlainObject(v)) paths(v, p).forEach((c) => out.add(c));
  }
  return out;
}

/** Drop from `doc` every path any base file already claims. */
function withoutClaimed(doc: Values, claimed: Set<string>, prefix = ""): Values {
  const out: Values = {};
  for (const [k, v] of Object.entries(doc)) {
    const p = prefix ? `${prefix}.${k}` : k;
    if (isPlainObject(v)) {
      const sub = withoutClaimed(v, claimed, p);
      if (Object.keys(sub).length) out[k] = sub;
    } else if (!claimed.has(p)) {
      out[k] = v;
    }
  }
  return out;
}

/** A values file always exists, even when it is empty: a missing valueFile fails the whole render. */
function valuesFile(path: string, doc: Values, header: string, note: string): GeneratedFile {
  const body = Object.keys(doc).length ? toYaml(doc) : "{}";
  return { path, text: `${header}\n${body}\n`, note };
}

export function buildTree(tree: ArgocdTree): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const releases = tree.releases.filter((r) => r.name.trim());
  const namespaces = tree.namespaces.filter((n) => n.name.trim());
  const valuesPath = tree.values.path ?? "";

  // ---- base layer -------------------------------------------------------
  // Written whole. There is no tree-root defaults.yaml to subtract against any
  // more — the chart's chain starts at <ns>/defaults.yaml, and subtracting
  // against a layer nobody applies silently drops the value.
  const base = new Map<string, Values>();
  releases.forEach((r) => base.set(r.id, buildValues(r.features, r.extraValues)));

  const claimed = new Set<string>();
  base.forEach((doc) => paths(doc).forEach((p) => claimed.add(p)));

  releases.forEach((r) => {
    files.push(
      valuesFile(
        `base/${slug(r.name)}.yaml`,
        base.get(r.id) ?? {},
        `${HEADER}\n# ${r.name} — environment-agnostic values, shared by every namespace that runs it.`,
        "environment-agnostic"
      )
    );
  });

  // ---- namespace layers -------------------------------------------------
  namespaces.forEach((ns) => {
    // A namespace runs every release in the tree; an entry only carries what it
    // overrides. The values file is written for all of them either way — its
    // existence in `<ns>/values/` is what puts the release in the fan-out, so a
    // release with nothing to override still needs an (empty) file.
    const fragments = new Map<string, Values>();
    releases.forEach((r) => {
      const entry = ns.releases.find((e) => e.release === r.id);
      fragments.set(r.id, entry ? buildValues(entry.features, entry.extraValues) : {});
    });

    // Shared across this namespace's releases AND not claimed by any base file
    // — see `withoutClaimed`: base merges after namespace defaults, so a
    // colliding key promoted here would never take effect.
    const nsDefaults = withoutClaimed(commonSubtree([...fragments.values()]), claimed);

    files.push(
      valuesFile(
        `${ns.name}/defaults.yaml`,
        nsDefaults,
        `${HEADER}\n# ${ns.name} — settings identical across this namespace's releases.`,
        `${ns.name} · shared`
      )
    );

    releases.forEach((release) => {
      const below = deepMerge(nsDefaults, base.get(release.id) ?? {});
      const doc = subtractDefaults(fragments.get(release.id) ?? {}, below);
      files.push(
        valuesFile(
          `${ns.name}/values/${slug(release.name)}.yaml`,
          doc,
          `${HEADER}\n# ${release.name} in ${ns.name} — only what differs. Applied last, so it wins.`,
          `${ns.name} · overrides`
        )
      );
    });
  });

  files.push({
    path: ROOT_APPSET_FILE_NAME,
    text: `${rootAppsetHeader(tree)}\n${toYaml(rootApplicationSet(tree, valuesPath))}\n`,
    note: "one Application per namespace directory",
  });

  files.push({
    path: "root-application.yaml",
    text: `${rootHeader(tree)}\n${toYaml(rootApplication(tree, valuesPath))}\n`,
    note: "the one object you apply by hand",
  });

  return files;
}

function rootAppsetHeader(tree: ArgocdTree): string {
  return [
    "# One Application per NAMESPACE DIRECTORY in this tree, each deploying the",
    `# '${tree.chart.appsetPath}' chart, which in turn fans out over that namespace's`,
    "# values/*.yaml. A new namespace is a new directory here and nothing else —",
    "# no manifest to add, no apply to run.",
    "# Deployed by root-application.yaml; do not apply it by hand.",
  ].join("\n");
}

/**
 * A `directories` generator over the tree root: every top-level directory is a
 * namespace except the few that hold values or reports, which are excluded by
 * name.
 *
 * Each generated Application deploys the `ms-applicationSet` chart, parameterised
 * with the namespace and this values repo. Keeping the per-release fan-out and
 * the three-file layering in that chart rather than writing them into every
 * values repo is the point: the layering rules live in one place, versioned with
 * the chart that applies them.
 */
function rootApplicationSet(tree: ArgocdTree, valuesPath: string): Values {
  const name = `${tree.rootAppName || "platform-root"}-set`;
  return {
    apiVersion: "argoproj.io/v1alpha1",
    kind: "ApplicationSet",
    metadata: { name, namespace: ARGOCD_NAMESPACE, labels: { app: name } },
    spec: {
      generators: [
        {
          git: {
            repoURL: tree.values.repoUrl,
            revision: tree.values.revision,
            directories: [
              { path: repoPath(valuesPath, "*") },
              ...NON_NAMESPACE_DIRS.map((dir) => ({ path: repoPath(valuesPath, dir), exclude: true })),
            ],
          },
        },
      ],
      template: {
        metadata: { name: "{{path.basename}}", labels: { app: name, "managed-by": "universal-chart" } },
        spec: {
          project: PROJECT,
          sources: [
            {
              repoURL: tree.chart.repoUrl,
              targetRevision: tree.chart.revision,
              path: tree.chart.appsetPath,
              helm: {
                // An empty parameter is left out rather than written as `""`:
                // the writer drops empty scalars anyway, and the chart's own
                // default for every one of these is the empty string, so
                // omitting it and setting it to "" mean the same thing.
                parameters: [
                  { name: "namespace", value: "{{path.basename}}" },
                  { name: "originRepoURL", value: tree.values.repoUrl },
                  { name: "originBranch", value: tree.values.revision },
                  { name: "originPath", value: valuesPath },
                  { name: "project", value: PROJECT },
                  { name: "destinationServer", value: DESTINATION_SERVER },
                  { name: "chartRepoURL", value: tree.chart.repoUrl },
                  { name: "chartRevision", value: tree.chart.revision },
                  { name: "chartPath", value: tree.chart.path },
                ].filter((p) => p.value !== ""),
              },
            },
          ],
          destination: { server: DESTINATION_SERVER, namespace: ARGOCD_NAMESPACE },
          syncPolicy: {
            automated: { prune: true, selfHeal: true },
            syncOptions: ["ServerSideApply=true"],
          },
        },
      },
    },
  };
}

function rootHeader(tree: ArgocdTree): string {
  return [
    "# ROOT app-of-apps: the ONE object you apply by hand. Bootstrapping is",
    "#",
    "#     kubectl apply -f root-application.yaml",
    "#",
    `# and nothing else. It deploys ${ROOT_APPSET_FILE_NAME} by name; everything after`,
    "# that reconciles from git. Adding a namespace or a release later is a git commit.",
    "#",
    "# prune is false on purpose: pruning the root ApplicationSet would cascade into",
    "# deleting every Application it generated and every workload those deploy.",
    `# It does not include itself — ${tree.rootAppName || "platform-root"} is what you bootstrap with,`,
    "# not something ArgoCD manages.",
  ].join("\n");
}

function rootApplication(tree: ArgocdTree, valuesPath: string): Values {
  const name = tree.rootAppName || "platform-root";
  return {
    apiVersion: "argoproj.io/v1alpha1",
    kind: "Application",
    metadata: { name, namespace: ARGOCD_NAMESPACE, labels: { app: name } },
    spec: {
      project: PROJECT,
      destination: { server: DESTINATION_SERVER, namespace: ARGOCD_NAMESPACE },
      // A directory source, not Helm: the file it deploys is already a finished
      // Kubernetes object, not a chart to render.
      source: {
        repoURL: tree.values.repoUrl,
        targetRevision: tree.values.revision,
        path: valuesPath || ".",
        directory: {
          // Naming the file outright, with recursion off, is what makes this
          // safe. Argo matches directory globs against paths relative to
          // source.path and a single `*` spans directory levels, so a pattern
          // like `*application.yaml` would also match a release named
          // `web-application` down in <ns>/values/ and Argo would apply a
          // values file as a manifest.
          recurse: false,
          include: ROOT_APPSET_FILE_NAME,
        },
      },
      syncPolicy: { automated: { prune: false, selfHeal: true }, syncOptions: ["ServerSideApply=true"] },
    },
  };
}
